"""Added notes column

Revision ID: 4ea322d8bfec
Revises: 35824b19bdc6
Create Date: 2024-10-03 09:15:28.290461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea322d8bfec'
down_revision: Union[str, None] = '35824b19bdc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'notes')
    # ### end Alembic commands ###
